/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-var-requires */

const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');
require('dotenv').config();
const environment = argv.environment;
const envDirectory = './apps/onboarding/src/environments';

function writeFileUsingFS(targetPath: string, environmentFileContent: string) {
  writeFile(targetPath, environmentFileContent, function (err: any) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
      console.log(process.env);
    }
  });
}

if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

writeFileUsingFS('./apps/onboarding/src/environments/environment.prod.ts', '');
writeFileUsingFS('./apps/onboarding/src/environments/environment.ts', '');

const isProduction = environment === 'prod';

const targetPath = isProduction
  ? './apps/onboarding/src/environments/environment.prod.ts'
  : './apps/onboarding/src/environments/environment.ts';

const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key screcy

  export const environment = {
    production: ${isProduction},
    baseUrl: 'https://api.themoviedb.org/3',
    apiKey: '${process.env.API_KEY}',
  };
`;

writeFileUsingFS(targetPath, environmentFileContent);
