// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key screcy

import { API_KEY } from '../config/config';

export const environment = {
  production: false,
  baseUrl: 'https://api.themoviedb.org/3',
  apiKey: API_KEY,
};
